name: main

on:
  push:
    branches: [main]

permissions:
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: wtnb75/actions/python@v1
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - uses: wtnb75/actions/wheel@v1
    - id: pdoc
      uses: wtnb75/actions/pdoc@v1
      with:
        output-dir: docs
        module: fmtparse
        other-options: --docformat google
    - uses: wtnb75/actions/merge-pages@v1
      with:
        dirs: "cover docs"
        #pydist: dist
    - name: Setup Pages
      uses: actions/configure-pages@v6
    - name: deploy pages
      uses: actions/deploy-pages@v5
      id: deployment
